// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    [Migration("20210421114329_initdb")]
    partial class initdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Measurement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<float>("Temperatur")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c56d122a-3f44-4b2e-9ead-512ddfe51adc"),
                            Date = new DateTime(2021, 4, 21, 13, 43, 29, 510, DateTimeKind.Local).AddTicks(2355),
                            Humidity = 0f,
                            Temperatur = 24f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
