// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    [Migration("20210423081656_extendedinitdata")]
    partial class extendedinitdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Measurement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<float>("Temperatur")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            ID = new Guid("bcf947c9-8732-49d5-9538-79efc2098709"),
                            Date = new DateTime(2021, 4, 23, 10, 16, 56, 482, DateTimeKind.Local).AddTicks(310),
                            Humidity = 0f,
                            Temperatur = 19f
                        },
                        new
                        {
                            ID = new Guid("38f92361-cda5-4b75-9517-3470b75bb364"),
                            Date = new DateTime(2021, 4, 23, 10, 16, 58, 484, DateTimeKind.Local).AddTicks(5054),
                            Humidity = 0f,
                            Temperatur = 19.5f
                        },
                        new
                        {
                            ID = new Guid("cf54c57a-359c-47ed-8ddf-80f457bd803c"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 0, 484, DateTimeKind.Local).AddTicks(5099),
                            Humidity = 0f,
                            Temperatur = 20.5f
                        },
                        new
                        {
                            ID = new Guid("f5237d2a-39a7-49e3-b5a8-abd784e0122e"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 4, 484, DateTimeKind.Local).AddTicks(5106),
                            Humidity = 0f,
                            Temperatur = 20.2f
                        },
                        new
                        {
                            ID = new Guid("3de03f70-daab-479c-994f-ff02329d0766"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 6, 484, DateTimeKind.Local).AddTicks(5110),
                            Humidity = 0f,
                            Temperatur = 20.3f
                        },
                        new
                        {
                            ID = new Guid("118183d4-256a-4228-b69a-237066798de7"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 8, 484, DateTimeKind.Local).AddTicks(5114),
                            Humidity = 0f,
                            Temperatur = 21f
                        },
                        new
                        {
                            ID = new Guid("35633c90-548c-4ed9-9a42-06e8797f6fec"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 10, 484, DateTimeKind.Local).AddTicks(5118),
                            Humidity = 0f,
                            Temperatur = 21.2f
                        },
                        new
                        {
                            ID = new Guid("b3806e46-b881-454d-9d49-8ec8b9e48c10"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 12, 484, DateTimeKind.Local).AddTicks(5135),
                            Humidity = 0f,
                            Temperatur = 21.5f
                        },
                        new
                        {
                            ID = new Guid("2151428a-61ae-4cb4-978d-62977fb87237"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 14, 484, DateTimeKind.Local).AddTicks(5139),
                            Humidity = 0f,
                            Temperatur = 21.3f
                        },
                        new
                        {
                            ID = new Guid("e561ed0e-771f-4762-9d82-772e514dd9b9"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 16, 484, DateTimeKind.Local).AddTicks(5143),
                            Humidity = 0f,
                            Temperatur = 20.9f
                        },
                        new
                        {
                            ID = new Guid("30282679-2cd5-469e-8ca4-22668f73bdc3"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 18, 484, DateTimeKind.Local).AddTicks(5147),
                            Humidity = 0f,
                            Temperatur = 20.8f
                        },
                        new
                        {
                            ID = new Guid("81a77806-eb59-447d-bd49-88edec5c8dee"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 20, 484, DateTimeKind.Local).AddTicks(5150),
                            Humidity = 0f,
                            Temperatur = 21.1f
                        },
                        new
                        {
                            ID = new Guid("da27016e-c929-4eb1-ac43-917e79a581e2"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 22, 484, DateTimeKind.Local).AddTicks(5154),
                            Humidity = 0f,
                            Temperatur = 20.94f
                        },
                        new
                        {
                            ID = new Guid("c2f9c76d-faa0-4778-bc65-08f78a96f531"),
                            Date = new DateTime(2021, 4, 23, 10, 17, 24, 484, DateTimeKind.Local).AddTicks(5157),
                            Humidity = 0f,
                            Temperatur = 20.6f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
